manual_seed: 2020
GPUs: [0]
base_dir_prev: seg/SegResidualUNet3D
description: baseline2

# model configuration
model:
  name: ResidualUNet3D
  in_channels: 1
  out_channels: 18
  f_maps: [16, 32, 64, 128]
  layer_order: cgr
  num_groups: 8


# trainer configuration
trainer:
  trainer_name: TrainerSegment
  validate_after_iters: 100
  log_after_iters: 10
  stop_after_nobest_iters: 2
  epochs: 100
  eval_score_higher_is_better: true
  amp: false

# loss function configuration
loss:
  name: BCEDiceLoss
  sigmoid_normalization: False

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.0001

# evaluation metric
eval_metric:
  name: DiceCoefficient

# learning rate scheduler configuration
# lr_scheduler:
#   name: ReduceLROnPlateau
#   mode: min
#   factor: 0.5
#   patience: 5

lr_scheduler:
  name: StepLR
  step_size: 5
  gamma: 0.8

# data loaders configuration
loaders:
  csv_path: DATA/fold.csv
  data_path: DATA/resize/norm/
  val_fold: 1
  batch_size: 1
  num_workers: 8
  manual_seed: 2020
  is_segmentation: true
  use_keypoint: false
  dist_thr: 4
  atlas: false
  gaussian: false