manual_seed: 2020
GPUs: [4]
base_dir_prev: KpBest/FOLD
description: FocalLoss

# model configuration
model:
  name: ResidualUNet3D
  in_channels: 1
  out_channels: 17
  layer_order: gcr
  f_maps: [16, 32, 64, 128]
  num_groups: 16
  final_sigmoid: false
  is_segmentation: true
  passing: false

# trainer configuration
trainer:
  validate_after_iters: 100
  log_after_iters: 10
  epochs: 200
  iters: 60000
  eval_score_higher_is_better: True

# loss function configuration
loss:
  name: KeyPointFocalLoss
  max_dist: 5

optimizer:
  learning_rate: 0.0001
  weight_decay: 0.0001

# evaluation metric
eval_metric:
  name: PointDistance
  distance_thre: 5

# learning rate scheduler configuration
# lr_scheduler:
#   name: ReduceLROnPlateau
#   mode: min
#   factor: 0.5
#   patience: 5

lr_scheduler:
  name: StepLR
  step_size: 3
  gamma: 0.6

# data loaders configuration
loaders:
  csv_path: /home/yuanfang/pytorch3dunet/DATA/fold.csv
  data_path: /home/yuanfang/pytorch3dunet/DATA/norm/
  val_fold: 1
  batch_size: 1
  num_workers: 8
  manual_seed: 2020